---
name: Run tests

env:
  VisualStudioVersion: "17.0"

on:
  push:
  pull_request:

jobs:
  pytest:
    uses: colcon/ci/.github/workflows/pytest.yaml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
